services:
    
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka: 
    image: confluentinc/cp-kafka:7.3.3
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-3
    depends_on:
      - kafka
    ports:
      - 8080:8080
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=base
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
        
  # Definición del servicio jobmanager para Apache Flink
  jobmanager:
    build:
      context: .  # Contexto de construcción para la imagen del contenedor
      dockerfile: Dockerfile  # Archivo Dockerfile utilizado para construir la imagen
    ports:
      - "8081:8081"  # Mapeo de puertos del contenedor al host para acceder a la interfaz web del JobManager
    volumes:
      - ./code:/tmp/scripts  # Volumen para montar un directorio del host en el contenedor
    command: jobmanager  # Comando que se ejecutará al iniciar este contenedor
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager  # Dirección RPC del JobManager
      JOB_MANAGER_RPC_PORT: 6123  # Puerto RPC del JobManager
      JOB_MANAGER_HEAP_SIZE: 1024m  # Tamaño de la memoria heap para el JobManager
      PARALLELISM_DEFAULT: 1  # Paralelismo predeterminado

  # Definición del servicio taskmanager para Apache Flink
  taskmanager:
    build:
      context: .  # Contexto de construcción para la imagen del contenedor
      dockerfile: Dockerfile  # Archivo Dockerfile utilizado para construir la imagen
    command: taskmanager  # Comando que se ejecutará al iniciar este contenedor
    depends_on:
      - jobmanager  # Dependencia del servicio taskmanager respecto al servicio jobmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager  # Dirección RPC del JobManager para la comunicación
      TASK_MANAGER_HEAP_SIZE: 1024m  # Tamaño de la memoria heap para el TaskManager
      TASK_MANAGER_NUMBER_OF_TASK_SLOTS: 4  # Número de slots de tarea para el TaskManager

  # Elastic Search
  elasticsearch:
    image: elasticsearch:7.17.25
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
    ports:
      - "9200:9200"

  # Kibana
  kibana:
    image: kibana:7.17.25
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    depends_on:
      - elasticsearch