FROM flink:1.18.0-scala_2.12
 
RUN apt-get update -y \
    && apt-get install -y python3 python3-pip
 
RUN pip install apache-flink==1.18.0 kafka-python

COPY ./jars/flink-connector-kafka-3.1.0-1.18.jar /opt/flink/lib/
COPY ./jars/kafka-clients-3.7.0.jar /opt/flink/lib/

WORKDIR /app
COPY . /app